# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_hardcore.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_hardcore.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_hardcore.ipynb 10
def foo(bar='foobar'):
    print(bar)
